// Common type definitions for the project
// Generated by fix-specific-interfaces.js

import { NavigationProp } from '@react-navigation/native';
import { StyleProp, ViewStyle, TextStyle } from 'react-native';

// Navigation types
export type AppNavigationProp = NavigationProp<any>;

// Form value types
export type FormValue = string | number | boolean | null;

// Test result types
export interface TestResult {
  success: boolean;
  message: string;
  data?: Record<string, any>;
  error?: string;
}

// Market configuration
export interface MarketConfig {
  market: string;
  features: Record<string, boolean>;
  locale?: string;
  currency?: string;
}

// User data
export interface UserData {
  id: string;
  email?: string;
  username?: string;
  [key: string]: any;
}

// Generic data record
export type DataRecord = Record<string, string | number | boolean>;
